# -*- coding: utf-8 -*-
"""EJERCICIO MAURO WAMBA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yaF7Qg9xMsNHsAlAjuL3D_wLRpqAUNGk

# Enunciado

Escribe un programa que evalúe las calificaciones de un grupo de estudiantes para determinar su promedio final. El programa debe filtrar las notas no válidas, que incluyen números fuera del rango de 0 a 100 y valores que no son numéricos. Las notas válidas deben ser utilizadas para calcular el promedio de cada estudiante. Si una nota es inválida, el programa deberá notificar el error y mostrar el nombre del estudiante junto con la descripción del error. Finalmente, el programa debe imprimir el nombre del estudiante y su calificación promedio basada solo en las notas válidas.


Ejemplo Entrada:

``` python
students = [
    {"nombre": "José", "notas": [85, 90, 78, -10]},
    {"nombre": "Carlos", "notas": [88, 72, 94, 102]},
    {"nombre": "María", "notas": [95, 85, 87, "A++"]}
]

```

Salida esperada:


``` python

Error en la nota de José: Nota inválida -10
José: Calificación final = 84.33
Error en la nota de Carlos: Nota inválida 102
Carlos: Calificación final = 84.67
Error en la nota de María: Nota inválida A++
María: Calificación final = 89.00

```

EJERCICIO MAURO WAMBA
"""

students = [
    {"nombre": "José", "notas": [85, 90, 78, -10]},
    {"nombre": "Carlos", "notas": [False, 72, 94, 102]},
    {"nombre": "María", "notas": [1, 92, 87, "A++"]}
]

for student in students:
  nombre = student["nombre"]
  notas = student ["notas"]

  print("Nombre:",nombre)
  print("Sus notas son:",notas)


  for nota in notas:
   if type(nota) == str:
    print("Error en la nota de",nombre,": nota invalida:",nota)
    notas.remove(nota)
   else:
    try:
     if type(nota) == bool:
      print("Error en la nota de",nombre,": nota invalida:",nota)
      notas.remove(nota)
    except nota == 1 or nota == 0:
      continue
    else: type(nota) == float
    if nota < 0 or nota > 100:
       print("Error en la nota de",nombre,": nota invalida:",nota)
       notas.remove(nota)

  try:
   notafinal = sum(notas)/len(notas)
   notafinal = round(notafinal,2)
   print("la nota final de ",nombre," es: ",notafinal)
  except ZeroDivisionError:
   print(nombre,"no tiene notas validas")